"""
One-shot script: appends API-BATCH-08 (GET /api/v1/Batches) to the batch pack JSON.
Run once; idempotent check prevents duplicate insertion.
"""
import json, pathlib, sys

PACK_PATH = pathlib.Path(
    r"C:\Users\Onyema Ifechukwu\Downloads\kardit_batch_api_test_agent_v3_1"
    r"\kardit_batch_api_test_agent_v3_1\data"
    r"\batch_microservice_functional_test_pack_v3_30_each.json"
)

BATCH08 = {
    "api_id": "API-BATCH-08",
    "name": "List Batches",
    "endpoint": "GET /api/v1/Batches",
    "test_case_count": 30,
    "functional_requirements": [
        "FR-BATCH-API-08-01",
        "FR-BATCH-API-08-02",
        "FR-BATCH-API-08-03",
        "FR-BATCH-API-08-04",
        "FR-BATCH-API-08-05",
        "FR-BATCH-API-08-06",
    ],
    "test_cases": [
        {
            "tc_id": "TC-API-BATCH-08-001",
            "scenario": "list_batches_default",
            "test_type": "Functional",
            "description": "GET /api/v1/Batches with no filters returns 200 and a paginated BatchListDto.",
            "precondition": "At least one batch exists in the tenant.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None},
            "expected_result": "200 OK with BatchListDto body containing page, pageSize, total, data array.",
        },
        {
            "tc_id": "TC-API-BATCH-08-002",
            "scenario": "list_batches_returns_pagination_metadata",
            "test_type": "Functional",
            "description": "Response body must contain page, pageSize, and total at the top level.",
            "precondition": "At least one batch exists.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None},
            "expected_result": "200 OK; body.page >= 1, body.pageSize >= 1, body.total >= 0.",
        },
        {
            "tc_id": "TC-API-BATCH-08-003",
            "scenario": "list_batches_items_have_required_fields",
            "test_type": "Schema",
            "description": "Each item in data[] must contain id, status, batchType, productId, and createdAt.",
            "precondition": "At least one batch exists.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None},
            "expected_result": "200 OK; every item in data[] has id, status, batchType, productId, createdAt.",
        },
        {
            "tc_id": "TC-API-BATCH-08-004",
            "scenario": "filter_by_status_completed",
            "test_type": "Functional",
            "description": "Filter Status=COMPLETED returns only batches with status COMPLETED.",
            "precondition": "At least one COMPLETED batch exists.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "COMPLETED"}, "body": None},
            "expected_result": "200 OK; all returned items have status=COMPLETED.",
        },
        {
            "tc_id": "TC-API-BATCH-08-005",
            "scenario": "filter_by_status_uploaded",
            "test_type": "Functional",
            "description": "Filter Status=UPLOADED returns only UPLOADED batches.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "UPLOADED"}, "body": None},
            "expected_result": "200 OK; all returned items have status=UPLOADED or data is empty.",
        },
        {
            "tc_id": "TC-API-BATCH-08-006",
            "scenario": "filter_by_status_failed",
            "test_type": "Functional",
            "description": "Filter Status=FAILED returns only FAILED batches.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "FAILED"}, "body": None},
            "expected_result": "200 OK; all returned items have status=FAILED or data is empty.",
        },
        {
            "tc_id": "TC-API-BATCH-08-007",
            "scenario": "filter_by_status_processing",
            "test_type": "Functional",
            "description": "Filter Status=PROCESSING returns only PROCESSING batches.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "PROCESSING"}, "body": None},
            "expected_result": "200 OK; all returned items have status=PROCESSING or data is empty.",
        },
        {
            "tc_id": "TC-API-BATCH-08-008",
            "scenario": "invalid_status_filter_rejected_or_empty",
            "test_type": "Negative",
            "description": "Supplying a non-existent status value should return 400/422 or an empty list.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "BOGUS_STATUS"}, "body": None},
            "expected_result": "400/422 or 200 with empty data array.",
        },
        {
            "tc_id": "TC-API-BATCH-08-009",
            "scenario": "filter_by_batch_type_card_creation",
            "test_type": "Functional",
            "description": "Filter BatchType=card-creation returns only card-creation batches.",
            "precondition": "At least one card-creation batch exists.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"BatchType": "card-creation"}, "body": None},
            "expected_result": "200 OK; all returned items have batchType=card-creation.",
        },
        {
            "tc_id": "TC-API-BATCH-08-010",
            "scenario": "filter_by_product_id",
            "test_type": "Functional",
            "description": "Filter ProductId=PRO-0001 returns only batches linked to that product.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"ProductId": "PRO-0001"}, "body": None},
            "expected_result": "200 OK; results are filtered to the requested productId.",
        },
        {
            "tc_id": "TC-API-BATCH-08-011",
            "scenario": "filter_by_bank_id",
            "test_type": "Functional",
            "description": "Filter BankId=<seeded-bank-id> returns only batches belonging to that bank.",
            "precondition": "Seeded bank ID is known.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"BankId": "{{seeded_bank_id}}"}, "body": None},
            "expected_result": "200 OK; results are scoped to the provided BankId.",
        },
        {
            "tc_id": "TC-API-BATCH-08-012",
            "scenario": "filter_by_maker_user_id",
            "test_type": "Functional",
            "description": "Filter MakerUserId returns only batches created by that user.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"MakerUserId": "tester"}, "body": None},
            "expected_result": "200 OK; each item in data[] has makerUserId matching the filter.",
        },
        {
            "tc_id": "TC-API-BATCH-08-013",
            "scenario": "filter_by_submitted_from",
            "test_type": "Functional",
            "description": "SubmittedFrom filters to batches submitted on or after the date.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SubmittedFrom": "2026-01-01T00:00:00Z"}, "body": None},
            "expected_result": "200 OK; all items have submittedForApprovalAt >= 2026-01-01T00:00:00Z.",
        },
        {
            "tc_id": "TC-API-BATCH-08-014",
            "scenario": "filter_by_submitted_date_range",
            "test_type": "Functional",
            "description": "SubmittedFrom + SubmittedTo defines an inclusive date window.",
            "precondition": "None specific.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SubmittedFrom": "2026-01-01T00:00:00Z", "SubmittedTo": "2026-12-31T23:59:59Z"}, "body": None},
            "expected_result": "200 OK; all items fall within the specified date range.",
        },
        {
            "tc_id": "TC-API-BATCH-08-015",
            "scenario": "filter_future_submitted_from_returns_empty",
            "test_type": "Edge",
            "description": "SubmittedFrom set far in the future should return an empty data array.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SubmittedFrom": "2099-01-01T00:00:00Z"}, "body": None},
            "expected_result": "200 OK with data=[] and total=0.",
        },
        {
            "tc_id": "TC-API-BATCH-08-016",
            "scenario": "invalid_date_format_rejected",
            "test_type": "Negative",
            "description": "Malformed date string in SubmittedFrom should be rejected.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SubmittedFrom": "not-a-date"}, "body": None},
            "expected_result": "400 or 422 returned.",
        },
        {
            "tc_id": "TC-API-BATCH-08-017",
            "scenario": "pagination_page_size_5",
            "test_type": "Functional",
            "description": "PageSize=5 returns at most 5 items in the data array.",
            "precondition": "More than 5 batches exist.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Page": "1", "PageSize": "5"}, "body": None},
            "expected_result": "200 OK; data array has at most 5 elements; pageSize=5 in response.",
        },
        {
            "tc_id": "TC-API-BATCH-08-018",
            "scenario": "pagination_page_2",
            "test_type": "Functional",
            "description": "Page=2 returns the second page of results.",
            "precondition": "More than 5 batches exist.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Page": "2", "PageSize": "5"}, "body": None},
            "expected_result": "200 OK; page=2 in response; items differ from page 1.",
        },
        {
            "tc_id": "TC-API-BATCH-08-019",
            "scenario": "pagination_excessive_page_size_rejected_or_capped",
            "test_type": "Edge",
            "description": "PageSize=9999 should be capped to server max or rejected.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"PageSize": "9999"}, "body": None},
            "expected_result": "200 with capped page size, or 400/422 rejected.",
        },
        {
            "tc_id": "TC-API-BATCH-08-020",
            "scenario": "pagination_page_zero_rejected",
            "test_type": "Negative",
            "description": "Page=0 is outside the valid 1-based range and should be rejected.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Page": "0"}, "body": None},
            "expected_result": "400 or 422 returned.",
        },
        {
            "tc_id": "TC-API-BATCH-08-021",
            "scenario": "pagination_negative_page_size_rejected",
            "test_type": "Negative",
            "description": "PageSize=-1 is invalid and should be rejected.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"PageSize": "-1"}, "body": None},
            "expected_result": "400 or 422 returned.",
        },
        {
            "tc_id": "TC-API-BATCH-08-022",
            "scenario": "sort_by_created_at_asc",
            "test_type": "Functional",
            "description": "SortBy=createdAt with SortDirection=asc returns items in ascending order.",
            "precondition": "Multiple batches exist.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SortBy": "createdAt", "SortDirection": "asc"}, "body": None},
            "expected_result": "200 OK; items sorted by createdAt ascending.",
        },
        {
            "tc_id": "TC-API-BATCH-08-023",
            "scenario": "sort_by_created_at_desc",
            "test_type": "Functional",
            "description": "SortBy=createdAt with SortDirection=desc returns items in descending order.",
            "precondition": "Multiple batches exist.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SortBy": "createdAt", "SortDirection": "desc"}, "body": None},
            "expected_result": "200 OK; items sorted by createdAt descending.",
        },
        {
            "tc_id": "TC-API-BATCH-08-024",
            "scenario": "invalid_sort_direction_rejected_or_defaulted",
            "test_type": "Negative",
            "description": "SortDirection=SIDEWAYS should be rejected or silently defaulted.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"SortBy": "createdAt", "SortDirection": "SIDEWAYS"}, "body": None},
            "expected_result": "400/422 or 200 with default sort applied.",
        },
        {
            "tc_id": "TC-API-BATCH-08-025",
            "scenario": "combined_status_and_date_range_filter",
            "test_type": "Functional",
            "description": "Status=COMPLETED + SubmittedFrom returns only COMPLETED batches in the date window.",
            "precondition": "At least one COMPLETED batch submitted after 2026-01-01.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"Status": "COMPLETED", "SubmittedFrom": "2026-01-01T00:00:00Z"}, "body": None},
            "expected_result": "200 OK; all items have status=COMPLETED and submittedForApprovalAt within range.",
        },
        {
            "tc_id": "TC-API-BATCH-08-026",
            "scenario": "unauthenticated_list_rejected",
            "test_type": "Security",
            "description": "Request with no Authorization header must be rejected.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None, "headers": {}},
            "expected_result": "401 Unauthorized.",
        },
        {
            "tc_id": "TC-API-BATCH-08-027",
            "scenario": "tenant_scope_isolation",
            "test_type": "Security",
            "description": "Authenticated tenant can only see their own batches.",
            "precondition": "Token is scoped to a specific tenant.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None},
            "expected_result": "200 OK; data contains only batches belonging to the authenticated tenant.",
        },
        {
            "tc_id": "TC-API-BATCH-08-028",
            "scenario": "foreign_tenant_filter_rejected_or_scoped",
            "test_type": "Security",
            "description": "TenantId=<foreign-tenant-uuid> should be rejected or ignored — cannot cross tenant boundary.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"TenantId": "ffffffff-ffff-ffff-ffff-ffffffffffff"}, "body": None},
            "expected_result": "403 or 200 scoped to own tenant only.",
        },
        {
            "tc_id": "TC-API-BATCH-08-029",
            "scenario": "bank_user_list_scope",
            "test_type": "Security",
            "description": "Bank-role user should see only batches associated with their bank.",
            "precondition": "Bank user token available.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {}, "body": None},
            "expected_result": "200 OK; list scoped to batches belonging to the bank user's institution.",
        },
        {
            "tc_id": "TC-API-BATCH-08-030",
            "scenario": "unknown_batch_type_filter_returns_empty_or_rejected",
            "test_type": "Negative",
            "description": "BatchType=non-existent-type should return empty list or 400/422.",
            "precondition": "None.",
            "input_data": {"method": "GET", "endpoint": "/api/v1/Batches", "query_params": {"BatchType": "non-existent-type"}, "body": None},
            "expected_result": "200 with data=[] or 400/422.",
        },
    ],
}

pack = json.loads(PACK_PATH.read_text(encoding="utf-8"))

# Idempotency: skip if already present
existing_ids = {ep["api_id"] for ep in pack["endpoints"]}
if "API-BATCH-08" in existing_ids:
    print("API-BATCH-08 already present — nothing to do.")
    sys.exit(0)

pack["endpoints"].append(BATCH08)
pack["total_endpoints"] = len(pack["endpoints"])

PACK_PATH.write_text(json.dumps(pack, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Done. Pack now has {pack['total_endpoints']} endpoints.")
